import {
	Alert,
	Box,
	Button,
	Center,
	Container,
	Group,
	Loader,
	LoadingOverlay,
	Stack,
	Title,
} from '@mantine/core';
import { IconRefresh } from '@tabler/icons';
import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import Link from 'next/link';
import Todo from '../component/Todo';
import { getAllTodos } from '../frontend_api/getAllTodos';

export default function Home() {
	const {
		data: todos,
		status,
		isLoading,
		refetch,
		error,
		isRefetching,
	} = useQuery(['getAllTodos'], () => getAllTodos());

	return (
		<div>
			<Head>
				<title>Next-todo</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container>
				<Stack my="lg">
					<Title order={1} align="center">
						Welcome
					</Title>

					<Center>
						<Link href="/todo/add" passHref>
							<Button component="a">
								Click here to add a todo item
							</Button>
						</Link>
					</Center>
				</Stack>

				<Group position="right">
					<Button
						mt="lg"
						leftIcon={<IconRefresh size={14} />}
						variant="outline"
						color="gray"
						size="xs"
						onClick={refetch}
					>
						Refresh
					</Button>
				</Group>

				<Box my="lg">
					{isRefetching && (
						<>
							<LoadingOverlay
								overlayOpacity={0.3}
								overlayColor="black"
								overlayBlur={1}
								loaderProps={{ color: 'white' }}
								visible={isRefetching || isLoading}
								zIndex={5}
							/>
						</>
					)}

					{status === 'error' && error && (
						<Alert title="An error occurred" color="red">
							{JSON.stringify(error)}
						</Alert>
					)}

					{isLoading && (
						<Center>
							<Loader />
						</Center>
					)}

					{status === 'success' && (
						<Stack>
							{todos.map((todo, index) => (
								<Todo key={todo.id} {...todo} />
							))}
						</Stack>
					)}
				</Box>
			</Container>
		</div>
	);
}
