import {
	Alert,
	Button,
	Center,
	Container,
	Loader,
	Stack,
	Title,
} from '@mantine/core';
import { useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import Link from 'next/link';
import Todo from '../component/Todo';
import { getAllTodos } from '../frontend_api/getAllTodos';

export default function Home() {
	const {
		data: todos,
		status,
		isLoading,
		error,
	} = useQuery(['getAllTodos'], () => getAllTodos());

	return (
		<div>
			<Head>
				<title>Next-todo</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container>
				<Title order={1}>Welcome</Title>

				<Link href="/todo/add" passHref>
					<Button component="a">Click here to add a todo item</Button>
				</Link>

				{status === 'error' && error && (
					<Alert title="An error occurred" color="red">
						{JSON.stringify(error)}
					</Alert>
				)}

				{isLoading && (
					<Center>
						<Loader />
					</Center>
				)}

				{status === 'success' && (
					<Stack>
						{todos.map((todo, index) => (
							<Todo key={todo.id} {...todo} />
						))}
					</Stack>
				)}
			</Container>
		</div>
	);
}
